import { Resource, Project, Holiday, ProjectStatus } from '../types';
import { RESOURCE_COLORS } from '../constants/colors';
import { formatDate, addDays } from './dateUtils';

export const generateTestData = (): { resources: Resource[]; projects: Project[]; holidays: Holiday[] } => {
  const today = new Date();
  
  const resources: Resource[] = [
    {
      id: '1',
      name: 'রাফিন আহমেদ',
      role: 'Frontend Developer',
      color: RESOURCE_COLORS[0],
    },
    {
      id: '2',
      name: 'তানভীর হাসান',
      role: 'Backend Developer',
      color: RESOURCE_COLORS[1],
    },
    {
      id: '3',
      name: 'সাদিয়া খাতুন',
      role: 'UI/UX Designer',
      color: RESOURCE_COLORS[2],
    },
    {
      id: '4',
      name: 'ইমরান হোসেন',
      role: 'QA Engineer',
      color: RESOURCE_COLORS[3],
    },
    {
      id: '5',
      name: 'নাফিসা আক্তার',
      role: 'DevOps Engineer',
      color: RESOURCE_COLORS[4],
    },
    {
      id: '6',
      name: 'আরিফ রহমান',
      role: 'Product Manager',
      color: RESOURCE_COLORS[5],
    },
  ];

  const projects: Project[] = [
    // রাফিন আহমেদ projects
    {
      id: 'p1',
      title: 'Pathao Rider App UI',
      description: 'Redesigning the rider mobile application interface',
      startDate: formatDate(addDays(today, -15)),
      endDate: formatDate(addDays(today, 5)),
      deadline: formatDate(addDays(today, 7)),
      workDaysNeeded: 15,
      resourceId: '1',
      priority: 'high',
      status: 'active',
      progress: 75,
      estimatedHours: 120,
      actualHours: 90,
      healthScore: 85,
    },
    {
      id: 'p2',
      title: 'Pathao Food Web',
      description: 'Building responsive web application for food delivery',
      startDate: formatDate(addDays(today, 8)),
      endDate: formatDate(addDays(today, 25)),
      deadline: formatDate(addDays(today, 30)),
      workDaysNeeded: 12,
      resourceId: '1',
      priority: 'medium',
      status: 'planning',
      progress: 10,
      estimatedHours: 80,
      actualHours: 8,
      healthScore: 92,
    },
    {
      id: 'p3',
      title: 'Pathao Design System',
      description: 'Creating unified design system for all Pathao products',
      startDate: formatDate(addDays(today, 30)),
      endDate: formatDate(addDays(today, 45)),
      deadline: formatDate(addDays(today, 50)),
      workDaysNeeded: 10,
      resourceId: '1',
      priority: 'low',
      status: 'planning',
      progress: 0,
      estimatedHours: 60,
      actualHours: 0,
      healthScore: 95,
    },
    
    // তানভীর হাসান projects
    {
      id: 'p4',
      title: 'Pathao API Gateway',
      description: 'Implementing microservices API gateway architecture',
      startDate: formatDate(addDays(today, -10)),
      endDate: formatDate(addDays(today, 10)),
      deadline: formatDate(addDays(today, 5)),
      workDaysNeeded: 20,
      resourceId: '2',
      priority: 'high',
      status: 'at-risk',
      progress: 60,
      estimatedHours: 100,
      actualHours: 85,
      healthScore: 45,
    },
    {
      id: 'p5',
      title: 'Pathao User DB Migration',
      description: 'Migrating user database to new infrastructure',
      startDate: formatDate(addDays(today, 12)),
      endDate: formatDate(addDays(today, 20)),
      deadline: formatDate(addDays(today, 22)),
      workDaysNeeded: 6,
      resourceId: '2',
      priority: 'high',
      status: 'planning',
      progress: 5,
      estimatedHours: 150,
      actualHours: 7,
      healthScore: 88,
    },
    {
      id: 'p6',
      title: 'Pathao Backend Optimization',
      description: 'Performance optimization of backend services',
      startDate: formatDate(addDays(today, 25)),
      endDate: formatDate(addDays(today, 40)),
      resourceId: '2',
      priority: 'medium',
      status: 'planning',
      progress: 0,
      estimatedHours: 90,
      actualHours: 0,
      healthScore: 90,
    },
    
    // সাদিয়া খাতুন projects
    {
      id: 'p7',
      title: 'Pathao Brand Guidelines',
      description: 'Establishing comprehensive brand guidelines and design standards',
      startDate: formatDate(addDays(today, -20)),
      endDate: formatDate(addDays(today, -5)),
      resourceId: '3',
      priority: 'medium',
      status: 'completed',
      progress: 100,
      estimatedHours: 40,
      actualHours: 38,
      healthScore: 100,
      completedDate: formatDate(addDays(today, -5)),
    },
    {
      id: 'p8',
      title: 'Pathao Customer Research',
      description: 'Conducting user research and customer journey mapping',
      startDate: formatDate(addDays(today, -2)),
      endDate: formatDate(addDays(today, 12)),
      resourceId: '3',
      priority: 'high',
      status: 'active',
      progress: 45,
      estimatedHours: 55,
      actualHours: 25,
      healthScore: 78,
    },
    {
      id: 'p9',
      title: 'Pathao Courier Prototype',
      description: 'Creating interactive prototypes for courier service',
      startDate: formatDate(addDays(today, 15)),
      endDate: formatDate(addDays(today, 35)),
      resourceId: '3',
      priority: 'medium',
      status: 'planning',
      progress: 0,
      estimatedHours: 65,
      actualHours: 0,
      healthScore: 92,
    },
    
    // ইমরান হোসেন projects
    {
      id: 'p10',
      title: 'Pathao App Testing',
      description: 'Comprehensive testing of mobile and web applications',
      startDate: formatDate(addDays(today, -5)),
      endDate: formatDate(addDays(today, 15)),
      resourceId: '4',
      priority: 'high',
      status: 'active',
      progress: 70,
      estimatedHours: 80,
      actualHours: 56,
      healthScore: 82,
    },
    {
      id: 'p11',
      title: 'Pathao Load Testing',
      description: 'Performance and load testing for peak traffic scenarios',
      startDate: formatDate(addDays(today, 18)),
      endDate: formatDate(addDays(today, 28)),
      resourceId: '4',
      priority: 'medium',
      status: 'planning',
      progress: 0,
      estimatedHours: 50,
      actualHours: 0,
      healthScore: 85,
    },
    {
      id: 'p12',
      title: 'Pathao Security Audit',
      description: 'Security vulnerability assessment and penetration testing',
      startDate: formatDate(addDays(today, 32)),
      endDate: formatDate(addDays(today, 50)),
      resourceId: '4',
      priority: 'high',
      status: 'planning',
      progress: 0,
      estimatedHours: 120,
      actualHours: 0,
      healthScore: 90,
    },
    
    // নাফিসা আক্তার projects
    {
      id: 'p13',
      title: 'Pathao CI/CD Setup',
      description: 'Setting up continuous integration and deployment pipelines',
      startDate: formatDate(addDays(today, -12)),
      endDate: formatDate(addDays(today, 8)),
      resourceId: '5',
      priority: 'high',
      status: 'active',
      progress: 85,
      estimatedHours: 60,
      actualHours: 51,
      healthScore: 88,
    },
    {
      id: 'p14',
      title: 'Pathao Cloud Infrastructure',
      description: 'Migrating and optimizing cloud infrastructure',
      startDate: formatDate(addDays(today, 10)),
      endDate: formatDate(addDays(today, 22)),
      resourceId: '5',
      priority: 'medium',
      status: 'planning',
      progress: 0,
      estimatedHours: 100,
      actualHours: 0,
      healthScore: 92,
    },
    {
      id: 'p15',
      title: 'Pathao Monitoring System',
      description: 'Implementing comprehensive monitoring and alerting system',
      startDate: formatDate(addDays(today, 25)),
      endDate: formatDate(addDays(today, 42)),
      resourceId: '5',
      priority: 'low',
      status: 'planning',
      progress: 0,
      estimatedHours: 70,
      actualHours: 0,
      healthScore: 95,
    },
    
    // আরিফ রহমান projects
    {
      id: 'p16',
      title: 'Pathao Expansion Strategy',
      description: 'Strategic planning for market expansion and growth',
      startDate: formatDate(addDays(today, -8)),
      endDate: formatDate(addDays(today, 7)),
      resourceId: '6',
      priority: 'high',
      status: 'overdue',
      progress: 50,
      estimatedHours: 40,
      actualHours: 32,
      healthScore: 25,
    },
    {
      id: 'p17',
      title: 'Pathao Market Analysis',
      description: 'Comprehensive market research and competitor analysis',
      startDate: formatDate(addDays(today, 10)),
      endDate: formatDate(addDays(today, 25)),
      resourceId: '6',
      priority: 'medium',
      status: 'planning',
      progress: 0,
      estimatedHours: 50,
      actualHours: 0,
      healthScore: 80,
    },
    {
      id: 'p18',
      title: 'Pathao 2025 Roadmap',
      description: 'Long-term strategic roadmap and vision planning',
      startDate: formatDate(addDays(today, 28)),
      endDate: formatDate(addDays(today, 45)),
      resourceId: '6',
      priority: 'low',
      status: 'on-hold',
      progress: 0,
      estimatedHours: 60,
      actualHours: 0,
      healthScore: 70,
    },
  ];

  // Sample Bangladesh holidays
  const holidays: Holiday[] = [
    {
      id: 'h1',
      name: 'শহীদ দিবস ও আন্তর্জাতিক মাতৃভাষা দিবস',
      date: '2024-02-21',
      type: 'national',
      recurring: true,
      description: 'International Mother Language Day',
    },
    {
      id: 'h2',
      name: 'স্বাধীনতা দিবস',
      date: '2024-03-26',
      type: 'national',
      recurring: true,
      description: 'Independence Day of Bangladesh',
    },
    {
      id: 'h3',
      name: 'বাংলা নববর্ষ',
      date: '2024-04-14',
      type: 'national',
      recurring: true,
      description: 'Bengali New Year',
    },
    {
      id: 'h4',
      name: 'মে দিবস',
      date: '2024-05-01',
      type: 'national',
      recurring: true,
      description: 'International Labour Day',
    },
    {
      id: 'h5',
      name: 'বিজয় দিবস',
      date: '2024-12-16',
      type: 'national',
      recurring: true,
      description: 'Victory Day of Bangladesh',
    },
    {
      id: 'h6',
      name: 'ঈদুল ফিতর',
      date: formatDate(addDays(today, 30)), // Example future date
      type: 'religious',
      recurring: false,
      description: 'Festival of Breaking the Fast',
    },
    {
      id: 'h7',
      name: 'ঈদুল আযহা',
      date: formatDate(addDays(today, 90)), // Example future date
      type: 'religious',
      recurring: false,
      description: 'Festival of Sacrifice',
    },
  ];

  return { resources, projects, holidays };
};